### ISSUE TITLE
Noob question : best way to parse/iterate resulset

### ISSUE THREAD

**Issue by pihomeserver** [adam-cowley/neode#103]
Hello

I perform a cypher request to my neo4j instance. The result is composed of 2 elements : summary and records

What the best approach to iterate/parse the returned elements to analyse them, including them properties ?

**Comment by adam-cowley** [comment]
That's a very broad question... what kind of analysis would you like to do?

**Comment by pihomeserver** [comment]
I'm lost in how i could parse the result of a cypher query. I see that result is an array of Record items but i'm pretty sure that there is a clean way to iterate or get properties of each returned elements
The structure of the result is quite unclear for me

**Comment by pihomeserver** [comment]
Maybe an example is better to help understand my point
Here is a cypher request to execute
`MATCH (users:Users)-[]-(comments:Comments)-[*..2]->(books:Books {ISBN: $ISBN}) RETURN books, comments, users`
So i implemented the request like below and i would like to know the best way to parse the resultset
```
  neo4j.cypher('MATCH (users:Users)-[]-(comments:Comments)-[*..2]->(books:Books {ISBN: $ISBN}) RETURN books, comments, users', {ISBN: req.query.ISBN})
  .then(result => {
    result.records.forEach(element => {
      .....
    });
    return res.status(200).json({ status: 'success', message: ''});
  })
  .catch((err) => {
		next(err);
	})
```
Do i have to hardcode the _fields array and add a new loop or is there a way to get the structure easily. I need to get all nodes (uniq) and relationships (inc properties)  ?
Hope it makes it more clear

**Comment by pihomeserver** [comment]
Searching examples and looking at tests specs, i understood the hydrate function ;-)
Just now i can't find how to get relationships
