### ISSUE TITLE
old parameter syntax `{param}` is no longer supported  "running-a-cypher-query" example

### ISSUE THREAD

**Issue by leoruba** [adam-cowley/neode#108]
https://github.com/adam-cowley/neode#running-a-cypher-query

instance.cypher('MATCH (p:Person {name: {name}}) RETURN p', {name: "Adam"})
    .then(res => {
        console.log(res.records.length);
    })

Gives:
Neo4jError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead

**Comment by adam-cowley** [comment]
Thanks for the heads up, I've updated the README.  The syntax should now be

```
instance.cypher('MATCH (p:Person {name: $name}) RETURN p', {name: "Adam"})
  .then(res => {
    console.log(res.records.length);
  })
```
