### ISSUE TITLE
multiple databases error

### ISSUE THREAD

**Issue by athencxss** [adam-cowley/neode#111]
`{ Neo4jError: Driver is connected to the database that does not support multiple databases. Please upgrade to neo4j 4.0.0 or later in order to use this functionality`

```
$ neo4j --version 
neo4j 3.5.14
```

**Comment by adam-cowley** [comment]
Due to the upgrade in drivers, you'll need version 0.3.8 to use this with 3.5 at the moment.  There's a fix for it but I haven't gotten around to it yet

**Comment by cue-parashar** [comment]
Can we re-open the issue & make it a feature where I have an option to select driver?
