### ISSUE TITLE
Joi validation of string does not allow empty string

### ISSUE THREAD

**Issue by BaalDev-Solutions** [adam-cowley/neode#112]
I had this error because sometimes one of my inputs was an empty string what I do not matter because that fields is not required.  I had to create another layer on neode to complement it and solve this and other matters.

Is there a way to tell the model how to Joi should validate each field?

**Comment by adam-cowley** [comment]
How have you set the property validation?

**Comment by BaalDev-Solutions** [comment]
Hi Adam, 

this is how I am setting them my models:

module.exports =
    ('Car',
    {
        //labels: [], empty labels produce an error
        [m.carId]: { primary: true, type: 'uuid' },
        [m.make]: 'number',
        [m.model]: 'number',
        [m.version]: 'string',
        [m.firstReg]: 'datetime',
        [m.price]: 'price',
        [m.imageUrl]: 'string',
        WANT_BARTER: {
            type: 'relationship',
            target: 'Car',
            direction: 'out',
            relationship: 'WANT_BARTER',
            properties: {
                [m.relationshipId]: 'string', // ? Implement Jorge can it be primary key
                date: 'datetime',
                [m.moneyProposal]: 'number',
                strength: 'number',
            },

            //eager: true, // <-- eager load this relationship
        },
    });

Do you mean that?

**Comment by adam-cowley** [comment]
Yeah that's right.  Which property is the error on?  

You should be able to do something like this:
```
  bar: {
        type: 'string',
        allow: '', // <-- allow empty string
    }
```

But I would suggest instead cleaning up the values so you're not storing empty strings in your database instead.

**Comment by BaalDev-Solutions** [comment]
I see, I read the documentation but I did not realize I could apply the Joi rules on my models

It is descripted below this line but in my opinion it is not clear how to use it because there is no example.
> Validation is provided by the Joi library. Certain data types (float, integer, boolean) will also be type cast during the data cleansing process. For more information on the full range of validation options, read the Joi API documentation.

Would you mind if I add an example to the Readme?

Thanks for you answer!

**Comment by adam-cowley** [comment]
That would be perfect, thank you.  Feel free to submit a pull request with the updated README
