### ISSUE TITLE
Slow Response

### ISSUE THREAD

**Issue by saibhaskerraju** [adam-cowley/neode#117]
Hi All,
Apologies if I am missing something here. When I query using neo4j-browser, the time taken is ~10-15ms but when I use the same query using this driver, it takes around ~470-520ms. I am not sure whether I am doing the right thing here. Below is the JS snippet I used.

`const instance = new Neode(uri, user, password, true);

var dayArr = ["2020_05_17", "2020_05_10"],
  userID = "5b186ae490d3bf0b45dfe4c4",
  fnlRes = [],
  querySkltn = `match(u:User{id:"${userID}"})-[:{fnldate}]->(p:Post) return p order by p.createdAt;`,
  relSkltn = `POSTED_ON_{date}|`,
  tempRel = "";

for (let index = 0; index < dayArr.length; index++) {
  tempRel = tempRel.concat(relSkltn.replace("{date}", dayArr[index]));
}
tempRel = tempRel.slice(0, -1);
querySkltn = querySkltn.replace("{fnldate}", tempRel);
console.log(querySkltn);
var t0 = performance.now();
instance.cypher(querySkltn).then((res) => {
  console.log(res);
  var t1 = performance.now();
  console.log("Call took " + (t1 - t0) + " milliseconds.");
  instance.close();
});`

**Comment by adam-cowley** [comment]
In theory that query is running through exactly the same driver and methods neo4j browser would be so it shouldn't be any slower.  Does that user have many posts for that date?   Is there an index or constraint on :User.id?

```
CREATE CONSTRAINT ON (u:User) ASSERT u.id IS UNIQUE;
```

Your query could be improved to use $parameters rather than a literal value for the user id but apart from that I don't see any issues.

```JS
var dayArr = ["2020_05_17", "2020_05_10"],
    userID = "5b186ae490d3bf0b45dfe4c4",
    fnlRes = [],
    querySkltn = "match(u: User{ id: $userID }) - [: { fnldate }] -> (p: Post) return p order by p.createdAt;"
relSkltn = POSTED_ON_{ date }|,
    tempRel = "";

for (let index = 0; index < dayArr.length; index++) {
    tempRel = tempRel.concat(relSkltn.replace("{date}", dayArr[index]));
}
tempRel = tempRel.slice(0, -1);
querySkltn = querySkltn.replace("{fnldate}", tempRel);
console.log(querySkltn);

var t0 = performance.now();

instance.cypher(
  querySkltn,
  { userID } // <-- user id as a parameter
).then((res) => {
    console.log(res);
    var t1 = performance.now();
    console.log("Call took " + (t1 - t0) + " milliseconds.");
    instance.close();
});
```
