### ISSUE TITLE
error TS1192: error TS1192:Module '"...../neode/types/index"' has no default export.

### ISSUE THREAD

**Issue by breitmark** [adam-cowley/neode#14]
Neode looks great, but with the missing default export it isn't usable from TypeScript with the constructor. Only fromEnv() is usable in TS.
Could you please define the default export or add a static 'create' function like fromEnv?

**Comment by adam-cowley** [comment]
Could you make the changes to types/index.d.ts and submit a pull request?

**Comment by breitmark** [comment]
I don't understand why, but the problem is gone

**Comment by mhoangvslev** [comment]
The problem still persists
