### ISSUE TITLE
Neode.withDirectory gets crazy with Typescript

### ISSUE THREAD

**Issue by breitmark** [adam-cowley/neode#15]
Typescript writes its .map files in the same directory as the compiled .js files. Please add a filter like:

var path = require('path');

{
        key: 'withDirectory',
        value: function withDirectory(directory) {
            var _this2 = this;

            var files = _fs2.default.readdirSync(directory);

            files.filter(function(file) {
                return path.extname(file).toLowerCase() === '.js';
            });
            
            files.forEach(function (file) {
                var model = file.replace('.js', '');
                var path = directory + '/' + file;
                var schema = require(path);

                return _this2.model(model, schema);
            });

            return this;
        }

**Comment by adam-cowley** [comment]
Thanks for the heads up!
