### ISSUE TITLE
AN ERROR OCCURRED WHILE EXECUTING SEARCH: Writing in read access mode not allowed. Attempted write to internal graph 0 (neo4j)

### ISSUE THREAD

**Issue by Vinayak-pawar** [adam-cowley/neode#169]
Neo4j bloom is throwing this error I tried everything from the internet but still facing this issue.
I want to  run betweenness centrality on my dataset but getting this error

**Comment by adam-cowley** [comment]
Please [raise issues for Neo4j bloom in the neo4j-bloom repository](https://github.com/neo4j-devtools/neo4j-bloom/issues)
