### ISSUE TITLE
Howto get from cypher result to object from model

### ISSUE THREAD

**Issue by breitmark** [adam-cowley/neode#17]
How can I convert the result of a cypher query to the corresponding model objects:

instance._neode.cypher('MATCH (s:Session)-[:foo]->(f:Foo) WHERE s.id=$sid AND f.id=$fid',
{
       fid: ...,
       sid: ...
}).then(function (result) {
      const session = result.records[0];
}

For session I have a model Session which I would like to use

**Comment by adam-cowley** [comment]
You can use the `.hydrate` or `.hydrateFirst` functions to convert a node into a Model.

```
return neode.cypher(cypher, params)
        .then(res => {
            return {
                foo: neode.hydrateFirst(res, 'f'),
                sessuib: neode.hydrateFirst(res, 's')
            };
        });
```

There is an example of this in the example repo:
https://github.com/adam-cowley/neode-example/blob/master/server.js#L77

**Comment by breitmark** [comment]
Thank you! Why don't you mention the other repositories for Neode here. I would appreciate if you would start a documentation folder with one page for each topic with code snippets.

**Comment by adam-cowley** [comment]
I'd definitely like to improve the documentation.  If you would be willing to help improve the documentation I'd be extremely grateful.   Let me know how you get on either way, I'd love to see what you've built with it.
