### ISSUE TITLE
NPM for 0.2.x ?

### ISSUE THREAD

**Issue by breitmark** [adam-cowley/neode#19]
When will you update the NPM to the current release branch?

**Comment by gooftroop** [comment]
To add on - is this project still alive?

**Comment by adam-cowley** [comment]
Yes it's still live.  I was hoping to find some time to do some more extensive testing but I haven't been able to yet.  Are you happy with how it works?  How are you finding the performance?

**Comment by adam-cowley** [comment]
0.2.7 has just been published to npm

**Comment by breitmark** [comment]
The 0.2.8 NPM throws
node_modules/neode/types/index.d.ts(4,1): error TS1185: Merge conflict marker encountered.
node_modules/neode/types/index.d.ts(6,1): error TS1185: Merge conflict marker encountered.
node_modules/neode/types/index.d.ts(7,1): error TS1185: Merge conflict marker encountered.

there are some leftovers from merging

**Comment by adam-cowley** [comment]
Sorry about that.  I've just published 0.2.9 with the merge conflicts removed.

**Comment by breitmark** [comment]
Can happen! That's teamwork ;-)

**Comment by gooftroop** [comment]
@adam-cowley Just getting started using it now, so I'll keep you posted!
