### ISSUE TITLE
[Bug] Neo4jError: Property values can only be of primitive types or arrays thereof

### ISSUE THREAD

**Issue by gooftroop** [adam-cowley/neode#23]
Ran into the error 'Neo4jError: Property values can only be of primitive types or arrays thereof' while attempting to create a node with a `point`.
The property shape is:
```
{
  createdAt: <default value of new Date().toISOString()>,
  location: {
    latitude: <float>,
    longitude: <float>,
  },
  userId: 1,
}
```

The code being ran is:
```
const result = await neo4j.model(CHECKIN).create({ ...args.data });
```

The query being executed is:
```
"CREATE
(this:Checkin { createdAt: $this_createdAt, id: $this_id, location: $this_location, userId: $this_userId })

RETURN

     this { 
        .*
        ,__EAGER_ID__: id(this)
        ,__EAGER_LABELS__: labels(this)
    }"
```

The `param` object is:
<img width="574" alt="params" src="https://user-images.githubusercontent.com/2867867/45853812-50102b80-bd15-11e8-806f-0433205626d6.png">

I'm still trying to debug, but I'm hoping you've encountered this issue before?

**Comment by adam-cowley** [comment]
I'm assuming this is down to the date not being converted to the native Neo4j type.  For argument sake can you try passing through a neo4j date while I work on a fix?

```
console.log(createdAt.toString()) // 2018-01-02T12:34:56.1234Z
const nativeDate = new neo4j.temporal.DateTime( startsAt.toString() ) ) 
```

https://www.adamcowley.co.uk/neo4j/neo4j-temporal-dates-javascript/

**Comment by gooftroop** [comment]
I think this will have the same issue as I noted in issue #22? The Joi validation will only allow strings to pass the `datetime` type

**Comment by gooftroop** [comment]
I'm able to create temporal `DateTime` using the following snippet from my schema:
```
createdAt: {
    default: () => new neo4j.types.DateTime.fromStandardDate(new Date()),
    required: true,
    type: 'datetime',
  },
```

However, this does fail the Joi validation for `datetime` since the value being validated is an Object rather than a string.

As a note, I'm using `neo4j-driver@1.7`

**Comment by adam-cowley** [comment]
I'll spend some time on handling each of the temporal and spatial types over the next couple of days.  Bear with me

**Comment by gooftroop** [comment]
Sounds good 👍 
Let me know if I can assist in anyway

**Comment by gooftroop** [comment]
verified fixed. nice! 🎉
