### ISSUE TITLE
Bad Merge conflict resolution

### ISSUE THREAD

**Issue by bboure** [adam-cowley/neode#26]
Hi @adam-cowley 
Looks like you did a mess here: https://github.com/adam-cowley/neode/blob/master/test/Model.spec.js 😄 
Since I don't know what you tried to do, I was not able to fix it. 
Can you have a look ?

**Comment by bboure** [comment]
in fact it's not the only place, the who test suite is broken ...

**Comment by adam-cowley** [comment]
Thanks for letting me know - looks like I missed the test suite.  I will be pushing an update with fixes to the other bugs.
