### ISSUE TITLE
Why does `Validator` method create its own error?

### ISSUE THREAD

**Issue by purplemana** [adam-cowley/neode#29]
There are several problems with this -
1. The code assumes certain properties, namely `details` and `path` are always available. However this is not the case if a schema declares a custom error this way -

        error: new Error("git happens")

    Because Joi replaces its own error object with the user supplied one.

2. The validation error details are lost, the code is not copying some important properties like `message`, limiting the information.

As `neode` falls back to `joi` for validation, why not simply reject with the same error object which the `validate` method returns!?

**Comment by adam-cowley** [comment]
The reason for this is that originally I could handle the validation errors in a generic way and/or pass the error through to a response in express.  I'm open to suggestions though.

**Comment by purplemana** [comment]
So I was working on fixing https://github.com/adam-cowley/neode/issues/30, found that the custom error message is being correctly returned by Joi, regardless of the position of the `error()` validator. The `Validator` method doesn't include this information in the wrapped error.

How about bubbling up Joi errors for now, if you need to wrap them in the future, maybe store them untouched in `ValidationError.error`. The complexity of conserving all the details of Joi errors while transforming them into own format doesn't feel justifiable at the moment. Thought?

**Comment by purplemana** [comment]
Closed with https://github.com/adam-cowley/neode/pull/33.
