### ISSUE TITLE
Custom errors not working as expected.

### ISSUE THREAD

**Issue by purplemana** [adam-cowley/neode#30]
For a schema like this

    {
        name: {
          type: "string",
          required: "true"
        },
        password: {
          type: "string",
          required: true,
          regex: /^[a-zA-Z0-9]{8,100}$/,
          error: () =>
            "Password must be between 8 to 100 characters and only alphabets and numbers are allowed"
        }
    }

The expected error message should be the one defined in the `error` field. However, the actual error being returned is:

    { 
      Error: ERROR_VALIDATION
        at new ValidationError (/mnt/c/Code/alchemist/node_modules/neode/build/ValidationError.js:21:124)
        at /mnt/c/Code/alchemist/node_modules/neode/build/Services/Validator.js:242:23
        at internals.Object._validateWithOptions (/mnt/c/Code/alchemist/node_modules/joi/lib/types/any/index.js:678:20)
        at module.exports.internals.Any.root.validate (/mnt/c/Code/alchemist/node_modules/joi/lib/index.js:138:23)
        at /mnt/c/Code/alchemist/node_modules/neode/build/Services/Validator.js:229:19
        at new Promise (<anonymous>)
        at Validator (/mnt/c/Code/alchemist/node_modules/neode/build/Services/Validator.js:228:10)
        at /mnt/c/Code/alchemist/node_modules/neode/build/Services/Create.js:28:40
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
      details: { password: [ 'string.regex.base' ] },
      input: undefined 
    }

Looking into the code, in `BuildValidationSchema`, the validation is built by iterating over the schema properties, chaining the Joi validators. This causes `error` to be added in the middle of the chain. The validators chained after it will influence the returned message. A fix would be to pluck the `error` key from the schema and add the `Joi.error` validator at the end.

Would be glad to submit a PR.

**Comment by adam-cowley** [comment]
This sounds useful.  If you could submit a PR for this I would be grateful.

**Comment by adam-cowley** [comment]
Could you create a Pull Request with the update?

**Comment by purplemana** [comment]
Please refer to my comments [here](https://github.com/adam-cowley/neode/issues/29#issuecomment-426969199). its better to return raw Joi errors.

**Comment by purplemana** [comment]
Also please merge [this](https://github.com/adam-cowley/neode/pull/33) if you are ok with the changes.

**Comment by purplemana** [comment]
Closed with https://github.com/adam-cowley/neode/pull/33.
