### ISSUE TITLE
Type for Collection.map is not correct

### ISSUE THREAD

**Issue by purplemana** [adam-cowley/neode#35]
Checkout this line:

https://github.com/adam-cowley/neode/blob/master/types/index.d.ts#L940

    map<U>(fn: (value: Node<any>, index: number, array: Array<Node<any>>) => U): U;

The return type should be `U[]` as map returns a collection.

**Comment by adam-cowley** [comment]
Can you submit a PR with the change for this please?

**Comment by purplemana** [comment]
Closed with https://github.com/adam-cowley/neode/pull/33.
