### ISSUE TITLE
Add Transaction support for Model and Relationship APIs.

### ISSUE THREAD

**Issue by purplemana** [adam-cowley/neode#40]
Neode supports transactions in the `batch` API. They should be added to ORM APIs as well.

Will submit a PR for the same. Thanks @adam-cowley  for merging the previous ones!

**Comment by purplemana** [comment]
@adam-cowley On my setup, running on Node 10.6, the Factory specs are failing as `toNumber` does not seem to be available in the `get('id')` code below:

    expect( node.get('id').toNumber() ).to.equal(3);

I went through the source to see where this method has been introduced, could you point me to it? Also I noticed that the specs are passing in your CI. So what's the mystery with `toNumber`?

**Comment by adam-cowley** [comment]
Is your ID an integer?  If not, you won't have the toNumber() function.  If you're looking for the internal ID, there is the `.identity()` method which returns the Neo4j Integer and  `.id()` function to return the Javascript Number (essentially `.identity().toNumber()`.

I like the PR a lot by the way, I've wanted to do this for a while.  Do you think it would also make sense to open up a transaction implicitly?

```
neode.beginTransaction();
neode.create('User', props)
  .then(() => neode.rollbackTransaction())
```

**Comment by purplemana** [comment]
@adam-cowley: The code is stable and tested a bit. Please feel free to review and merge. 

Also, could you fix the currently broken test cases? I will make a different PR to add transaction tests once the existing are fixed.
