### ISSUE TITLE
Incorrect type signature

### ISSUE THREAD

**Issue by purplemana** [adam-cowley/neode#42]
The signature for `Model.relationship` method is incorrect. It's missing the `type` parameter.

https://github.com/adam-cowley/neode/blob/656746d184416641cfeb3fc5794905250bde6ff1/types/index.d.ts#L622

In addition to this, Relationship Types should be defined.

Submitting a PR for this.

**Comment by purplemana** [comment]
https://github.com/adam-cowley/neode/pull/41 fixes this.

**Comment by Steve-Nzr** [comment]
Hi, Any update(s) ? Thanks.
