### ISSUE TITLE
Unique Constraints

### ISSUE THREAD

**Issue by ghbrown60640** [adam-cowley/neode#46]
Are unique constraints supported? I think I'm doing the right stuff but it keeps allowing me to create nodes with the same email address. Using version 0.2.10. Here's my model:
module.exports =  {
    person_id: {
        primary: true,
        type: 'uuid',
        // Creates an Exists Constraint in Enterprise mode
        required: true,
    },
    name: {
        type: 'string',
        required: true

    },
    email: {
        type: 'string',
        required: true,
        email: true,
        index: true,
        unique:true

    }
}

Here's my code: 
var Neode = require('neode');
const neo4jdb = new Neode('bolt://localhost:7687', 'neo4j', 'graphdb');
neo4jdb.withDirectory(__dirname+'/../models');
const createPerson = (person) => {
  var person = neo4jdb.model("Person").create(person).then(person =>
  {
    neo4jdb.close();
    return person;

  });
  return person;

}

module.exports.createPerson = createPerson

**Comment by adam-cowley** [comment]
Your model looks good but it won't automatically create the schema for you.  You'll need to do that programatically.

```js
instance.schema.install()
    .then(() => console.log('Schema installed!'))
```

If you're setting a property as unique then you don't need to set `index: true` as that will be taken care of for you.

**Comment by ghbrown60640** [comment]
Works Thanks!
