### ISSUE TITLE
Typescript property types out of date

### ISSUE THREAD

**Issue by HyenaCros** [adam-cowley/neode#47]
The types file doesn't allow type 'relationships', 'node', etc.

**Comment by adam-cowley** [comment]
Could you submit a PR to fix this please?  My typescript skills are sadly lacking at the moment.

**Comment by steve-nzr** [comment]
@HyenaCros https://github.com/adam-cowley/neode/pull/53 should've fixed it ;)

**Comment by adam-cowley** [comment]
@HyenaCros did the PR solve the issue?  This should be in the latest version.

**Comment by steve-nzr** [comment]
Yes !
