### ISSUE TITLE
".create("label", {property1 : "a" ...})" creates empty nodes on the db

### ISSUE THREAD

**Issue by Gaben01** [adam-cowley/neode#49]
Hello I'm new to everything related to neo4j and I've decided to try out your module.
Right now I'm having an issue, I'm simulating a registration to a website.

I receive the form as a json object
```
{
	"name": "Elena",
	"surname": "Fiera",
	"email": "elenafiera@gmail.com",
	"password": "miciomiciomiaomiao",
	"type": "HMM"
}
```

then after being converted to object, it is passed to the "createNode" method as "properties".

```
    /**
     * createNode -
     * it runs the creation of a new node
     * @param {Object} properties 
     * @param {Object} cb - callaback function
     */
    createNode: function (label, properties, cb) {
        var message = "succes"
        instance
            .model(label)
            .create(properties)
            .then(
                result => {
                    cb(message);
                },

                error => {
                    message = this.errorHandler(error);
                    cb(message);
                })
    }
```

(There you have the "User" model)
```
const User = {
    labels: ["User"],
    "name" : "name",
    "surname": "string",
    "email": "string",
    "password" : "string",
    "type" : "string",
};
```

Everything seems fine to me but on neo4j this is the result:

<img width="1263" alt="schermata 2019-02-25 alle 12 24 01" src="https://user-images.githubusercontent.com/39793342/53335149-f848a280-38fa-11e9-81d5-6577f93a4004.png">

As you can see none of the properties gets set in the new node, like if I've just created an empty "User" node.
I tried to pass different object to "create()" and I also tried to use just "create()" without "model()" but nothing, the result doesn't change... am I missing something? can you give me some suggestion?

**Comment by adam-cowley** [comment]
The code looks good to me. The call to `instance.create(label, props)` calls the same method that your code does under the hood.How is the model defined and how are you calling the createNode function?On 25 Feb 2019 11:49, Gaben01 <notifications@github.com> wrote:Hello I'm new to everything related to neo4j and I've decided to try out your module.
Right now I'm having an issue, I'm simulating a registration to a website.
I receive the form as a json object
{
	"name": "Elena",
	"surname": "Fiera",
	"email": "elenafiera@gmail.com",
	"password": "miciomiciomiaomiao",
	"type": "HMM"
}

then after being converted to object, it is passed to the "createNode" method as "properties".
    /**
     * createNode -
     * it runs the creation of a new node
     * @param {Object} properties 
     * @param {Object} cb - callaback function
     */
    createNode: function (label, properties, cb) {
        var message = "succes"
        instance
            .model(label)
            .create(properties)
            .then(
                result => {
                    cb(message);
                },

                error => {
                    message = this.errorHandler(error);
                    cb(message);
                })
    }

(There you have the "User" module)
const User = {
    labels: ["User"],
    "name" : "name",
    "surname": "string",
    "email": "string",
    "password" : "string",
    "type" : "string",
};

Everything seems fine to me but on neo4j this is the result:

As you can see none of the properties gets set in the new node, like if I've just created an empty "User" node.
I tried to pass different object to "create()" and I also tried to use just "create()" without "model()" but nothing, the result doesn't change... am I missing something? can you give me some suggestion?

**Comment by Gaben01** [comment]
Thanks for the fast response.
The model is defined in a separated file then in a file called service_db_connector I have this code

```
const neode = require('neode')
    .fromEnv()
    .with({
        User: require("../models/model_user"),
    });

module.exports = neode;

```
the method "createNode()" gets called from this method register user
```
/**
     * registerUser - 
     * it runs the creation of a new user
     * @param {Object} newUser 
     */
    registerUser : function(newUser, cb){
        const label = "User";
        dbWriter.createNode(label, newUser, cb);
    },
```

which is called by this 

```
/**
 * /user - 
 * route to create a new basic user
 */
router
    .route("/user/sign")
    .post((request, response) => {
        userHandlers.registerUser(request.body, function(result){
            return response.status(200).send(result);
        });     
    });
```

**Comment by adam-cowley** [comment]
How about module_user.js? It's the User object exported correctly?On 25 Feb 2019 12:47, Gaben01 <notifications@github.com> wrote:Thanks for the fast response.
The model is defined in a separated file then in a file called service_db_connector I have this code
const neode = require('neode')
    .fromEnv()
    .with({
        User: require("../models/model_user"),
    });

module.exports = neode;


the method "createNode()" gets called from this method register user
/**
     * registerUser - 
     * it runs the creation of a new user
     * @param {Object} newUser 
     */
    registerUser : function(newUser, cb){
        const label = "User";
        dbWriter.createNode(label, newUser, cb);
    },

which is called by this
/**
 * /user - 
 * route to create a new basic user
 */
router
    .route("/user/sign")
    .post((request, response) => {
        userHandlers.registerUser(request.body, function(result){
            return response.status(200).send(result);
        });     
    });

**Comment by Gaben01** [comment]
> How about module_user.js? It's the User object exported correctly?On 25 Feb 2019 12:47, Gaben01 <notifications@github.com> wrote:Thanks for the fast response. The model is defined in a separated file then in a file called service_db_connector I have this code const neode = require('neode') .fromEnv() .with({ User: require("../models/model_user"), }); module.exports = neode; the method "createNode()" gets called from this method register user /** * registerUser - * it runs the creation of a new user * @param {Object} newUser */ registerUser : function(newUser, cb){ const label = "User"; dbWriter.createNode(label, newUser, cb); }, which is called by this /** * /user - * route to create a new basic user */ router .route("/user/sign") .post((request, response) => { userHandlers.registerUser(request.body, function(result){ return response.status(200).send(result); }); }); —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

This way should be fine (?)

```
const User = {
    labels: ["User"],
    "name" : "name",
    "surname": "string",
    "email": "string",
    "password" : "string",
    "type" : "string",
};

module.exports = function(){
    return User;
}
```

**Comment by adam-cowley** [comment]
OK I see now. You're exporting a function which Neode won't call implicitly to get the return value. It will be expecting an object. You can either change the file to export the object rather than a function or call the function as you're defining the model.

**Comment by Gaben01** [comment]
> OK I see now. You're exporting a function which Neode won't call implicitly to get the return value. It will be expecting an object. You can either change the file to export the object rather than a function or call the function as you're defining the model.

I'm so dumb... thanks a lot man for your help 👍 now it works

**Comment by adam-cowley** [comment]
No worries, I had problems with this myself.

Your route could look something like this:
```
/**
 * /user - 
 * route to create a new basic user
 */
router
    .route("/user/sign")
    .post((request, response) => {
        userHandlers.registerUser(request.body, function(result){
            result.toJson()
              .then(json =>response.status(201).send(json) )
        });     
    });
```
It looks like you're also missing a `return` in registerUser.  

My routes look something like this:

```
router.post(
    '/:site_id/visits', 
    validator({ ... }), // neode uses Joi so you can use that without any more dependencies
    (req, res, next) => {
        const { token } = req;
        const site = req.params.site_id

        const body = Object.assign({}, req.body, { site, token });

        neode.create('Visit', body) 
            .then(res => res.toJson())
            .then(json => res.status(HTTP_CREATED).send(json))
            .catch(e => next(e));
});
```

**Comment by Gaben01** [comment]
Thanks for the pro tips, I'm kinda new to the the world of node too, so everything I'm doing are just tests to learn it, I'm lucky that I already know js and I don't have to learn it as well.

**Comment by adam-cowley** [comment]
No worries, good luck!
