### ISSUE TITLE
bug in instance.extend(original, new, schema) function

### ISSUE THREAD

**Issue by tvanbeek** [adam-cowley/neode#5]
Hey great work, I found a little bug tho:

In ModelMap.js on line 143 it says:

`labels.push(name);`

But this should be changed to:

`labels.push(as);`

Because otherwise the original label is added to the new model twice. In my code I do this for instance:

`neode.extend('Artwork', 'Sculpture');`

which results in the following model:

`_model._labels: ['Artwork', 'Artwork']`

But with my proposed change it will result in 

`_model._labels: ['Artwork', 'Sculpture']`

**Comment by adam-cowley** [comment]
Good spot.  I've just pushed a fix and published `v0.1.13` to npm
