### ISSUE TITLE
i need add new property 

### ISSUE THREAD

**Issue by cohedz** [adam-cowley/neode#52]
eg: in model  user i define

name:'String',
dob:'String'

I want to create new user have 

{
   name:'Hung',
  dob:'31-03-2019',
  gender:'male'
}

Who has the solution?
please help me

**Comment by adam-cowley** [comment]
You'll need to add another line to your model file:

```
gender: 'string'
```

**Comment by cohedz** [comment]
but it need to restart , do you have solution to add new attr but do'nt restart server?

**Comment by adam-cowley** [comment]
There is no way to do this without modifying the files and restarting the application.  If you are in a situation where you cannot restart or redeploy an application then you should really be defining more a robust set of requirements up front.
