### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by mhoangvslev** [adam-cowley/neode#60]
Hello, 

Is there a limit on the maximum number of transaction?

In a test I have 3000 objects to handle with 3 operations (create - merge - relate), so I guess is 9000 transactions overall.

The console returns this error
`browser-channel.js:219 WebSocket connection to 'ws://localhost:7687/' failed: net::ERR_FAILED`

Different things I tried;
1. close driver, open new session
2. close driver, create new db instance with model

Is there anything we can do?

**Comment by mhoangvslev** [comment]
Maybe because of the fact that in each MergeOn cal, we open and close a session. In my async function I waited for mergeOn to complete before moving on (await). I think batch() is a solution, but is there a way to call mergeOn, relateTo in a loop of 10k iterations?

**Comment by adam-cowley** [comment]
If you're running an import query of this size then I would suggest you use a cypher statement instead.  The timeouts are most likely due to garbage collection on the neo4j instance stopping any other threads from processing.  

Have you got any code that I can take a look at?
