### ISSUE TITLE
how to paginate a query?

### ISSUE THREAD

**Issue by Otoru** [adam-cowley/neode#65]
Writing a query manually, I use the `SKIP` and `LIMIT` parameters to do pagination.
how to do this with ogm?

**Comment by Shubhamnegi** [comment]
Are you are using .all() function to fetch nodes? If yes then it does have options for order, limit and skip.
```
all(properties?: object, order?: string | Array<any> | object, limit?: number, skip?: number): Promise<NodeCollection>
```

**Comment by Otoru** [comment]
Really, missed my attention while reading the documentation.
Thank you.
