### ISSUE TITLE
Incorrect validation on update node

### ISSUE THREAD

**Issue by Shubhamnegi** [adam-cowley/neode#66]
Update functions throw a validation error if the values which are being updated doesn't include the properties marked as required in the model.  For eg.  property a,b  are marked as required, then while updating property c, update function throws validation error for a and b as they are marked as required in the model, here I don't wish to update a and b.

**Comment by adam-cowley** [comment]
Do you have any code samples that I can take a look at?

**Comment by robotgryphon** [comment]
From basically a fresh install, using ts-node, typescript (latest), dotenv, and neode:

```typescript
import neode from "neode";

const instance = neode.fromEnv();

instance.model("Test", {
  test_id: {
    primary: true,
    type: "string",
    required: true
  },

  name: {
    type: "string"
  },

  isTest: {
    type: "boolean",
    required: false
  }
});

let run = async () => {
  const model = instance.model("Test");

  let node = await model.create({
    test_id: "node.test.1",
    name: "Test Node",
    isTest: true
  });

  let updatedNode = await node.update({
    name: "Test Node Updated"
  });

  await updatedNode.delete();

  console.debug("Node deleted.");
};

run();
```

![image](https://user-images.githubusercontent.com/8529636/61584374-701aa200-ab14-11e9-9189-debfb59c1575.png)

**Comment by Shubhamnegi** [comment]
This is what I did to update node while skipping validation check.
`var query =
      "match(j:Journal) where j.orderId = {orderId} set j+= {properties} return j";

    const result = await instance.cypher(query, {
      orderId: orderId,
      properties: data
    });
`
