### ISSUE TITLE
how to get a relationships of node without eager loading?

### ISSUE THREAD

**Issue by Otoru** [adam-cowley/neode#67]
I have an object that I got used to the `instance.findById` and would like to get the relationships of this object, and it does not have eager loading in its definition.

How could I do that?

**Comment by Shubhamnegi** [comment]
User query builder to get relationships
Use the below link from the document
https://github.com/adam-cowley/neode#query-builder

**Comment by adam-cowley** [comment]
As long as you have `eager: true` set in your relationship definition, findById will eagerly load it.

https://github.com/adam-cowley/neode#eager-loading

Feel free to  open a new issue if this doesn't answer the question.
