### ISSUE TITLE
Can properties be arrays ?

### ISSUE THREAD

**Issue by mpigorini** [adam-cowley/neode#68]

**Comment by marcoswca** [comment]
Hi @mpigorini, according to neo4j the properties are these:

Number, an abstract type, which has the subtypes Integer and Float
String
Boolean
The spatial type Point
Temporal types: Date, Time, LocalTime, DateTime, LocalDateTime and Duration

If you want an array as a property you can create a new Node and relationships

**Comment by mpigorini** [comment]
hi @marcoswca, you think that is a good idea create a node called phones number and other cellphones number. and after use they to save an array of phones ?. Neo4j allow work with array, i dont know why i cant do this with neode. However i solved my problem using others tricks

**Comment by marcoswca** [comment]
I think you could create a schema like this.e
![model](https://user-images.githubusercontent.com/9269700/63051336-6dad2d00-beb3-11e9-9466-759ca60054c9.png)

**Comment by mpigorini** [comment]
@marcoswca I know, but you think that it is a good idea ?. I don't agree
