### ISSUE TITLE
is this production ready?

### ISSUE THREAD

**Issue by antonioaltamura** [adam-cowley/neode#7]
Hello, I want to use this OGM for a project, how far is it from being production ready?
There are known unsolved bug currently?

**Comment by adam-cowley** [comment]
As far as I'm aware nobody is using this in production yet.  There are unit tests in the repository but coverage is far from complete.  If you would like to help iron out any bugs then I would be grateful for your help.  I also need to work on support for the new temporal data types in 3.4.

**Comment by antonioaltamura** [comment]
I ended up building my data model ES& classes with `save()` and `getById()` methods and doing query manually.

Congrats for your work, but I'm not skilled enough to actually help you :)

**Comment by AngefloMusic** [comment]
I almost used this in production at my last company with the intention to maintain the project and put in bug fixes, essentially run it off a fork, but Neo4j was dropped from the project architecture before we could implement it

**Comment by AngefloMusic** [comment]
High ups didn't give approval for the use of an external product

**Comment by AngefloMusic** [comment]
@antonioaltamura Anything can be production ready, might mean more work for you, but this is a good example where maybe whatever you're doing can contribute to the community to help make tools like this ready for production scrutiny.

**Comment by adam-cowley** [comment]
Closing this for now.  Feel free to open another one in future if necessary.
