### ISSUE TITLE
update joi to @hapi/joi

### ISSUE THREAD

**Issue by a88zach** [adam-cowley/neode#71]
joi has moved to @hapi/joi.  The package should be updated to reference the new location to remove warnings and ensure the latest version is used by consumers

 https://www.npmjs.com/package/joi

**Comment by a88zach** [comment]
https://github.com/adam-cowley/neode/commit/b27b4984725af45743907f8420e2353ecda00bfc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29

If you don't remove joi from the dependencies, we will still get the warnings as consumers of this package

**Comment by ScottWallace** [comment]
I'd take the warnings right now...

Big-time busted in 0.2.21.  Need to reference @hapi/joi in all requires, right now can't deliver to Google Firebase functions.  Yowch, I'm shut down.

Changing requires in "build/Services/Validator.js" and "src/Services/Validator.js" to "@hapi/joi" should do it.

**Comment by ScottWallace** [comment]
Got back to work by changing package.json reference to "neode": "0.2.18" (removed caret), temporarily.

**Comment by adam-cowley** [comment]
Sorry, lesson learned.  Never push code at 23:00.   I released v0.3 a little earlier with the fix to this.
