### ISSUE TITLE
is there a way to deep eager ?

### ISSUE THREAD

**Issue by jclappiway** [adam-cowley/neode#73]
Hi, 

can't make eager loading on 2 level depth. is it intended ?
Seeing the const MAX_EAGER_DEPTH I was expecting it to work.

**Comment by adam-cowley** [comment]
Eager should be loaded up to MAX_EAGER_DEPTH.  Can I take a look at your model definitions?

**Comment by jclappiway** [comment]
I made it working on nodes but not on relationships. Can't find the example anymore I'm using nodes finally
