### ISSUE TITLE
considering scalar functions in schema definition?

### ISSUE THREAD

**Issue by buzzeins** [adam-cowley/neode#77]
Hi, ist there a proper way to consider Neo4J scalar functions in a schema definition? 

For example TIMESTAMP():

```
CREATE (:Post {created_at: TIMESTAMP()})
```

Thanks

**Comment by adam-cowley** [comment]
Good question.  Specifically on timestamp, I would suggest using a `DateTime` or `LocalDateTime` so you get the benefit of `Duration`s. (more info here: https://adamcowley.co.uk/neo4j/temporal-native-dates/).  Alternatively, you could just pass `Date.now()` which does the same job.

```
timestamp: {
  type: 'integer',
  default: () => Date.now()
}
```

I can't think of any others that you would use off the top of my head.  Is there anything else that you'd find useful?

**Comment by buzzeins** [comment]
thanks :D
