### ISSUE TITLE
export hydrateNode function.

### ISSUE THREAD

**Issue by Shubhamnegi** [adam-cowley/neode#78]
Like hydrate and hydrate first there is a function in the factory named "hydrateNode". Internally hydrate and hydrate node use this function to convert Node object which provides me access to functions like toJSON(). Can we please export this function so that it can be used directly. 

Currently i am trying to fool the library by doing something like this.
```
instance.hydrateFirst({ records: [item] }, "modelName")
```

**Comment by adam-cowley** [comment]
You should be able to use this as in the example above.  Is it just that the function isn't in the types file?
