### ISSUE TITLE
how to get data some object not using result.get("prototype")

### ISSUE THREAD

**Issue by hoanghiep1x0** [adam-cowley/neode#81]
Is there a way to get an object all attributes instead of using get ("prototype") #support

**Comment by adam-cowley** [comment]
Can you provide an example of what you would like to do?

**Comment by hoanghiep1x0** [comment]
var profile = await People.first({ id: user_id });
    
 let result = {                
                        id: profile.get('id'),
                        uuid: profile.get('uuid'),
                        name: profile.get("name"),
                        alias: profile.get("alias"),
                        about: profile.get("about"),
                        mail: profile.get("mail"),
                        cover_full: profile.get("cover_full"),
                        cover: profile.get("cover"),
                        avatar: profile.get("avatar"),
                        phone: profile.get("phone"),
                        birthday: profile.get("birthday"),
                        address: profile.get("address"),
                        web: profile.get("web"),
                        fb: profile.get("fb"),
                        gg: profile.get("gg"),
                        tw: profile.get("tw"),
                        band: profile.get("band"),
                        stt: profile.get('stt')
}


I find it too verbose

**Comment by adam-cowley** [comment]
You can either do
```js
let result = profile.properties()
```
or
```js
let result = await profile.toJson()
```
