### ISSUE TITLE
Cannot read property 'Create' of undefined

### ISSUE THREAD

**Issue by taylor009** [adam-cowley/neode#83]
I'm trying to create a node from a post route but it errors.

Here is how it looks like in my route:

>  neode.create('Person', {
            name         : req.body.name,  
        }).then(result =>
        {
            logger.info('Successfully created Node in Neo4j');
            res.send(result);
            next();
        }).catch(error =>
        {
            logger.error(`Error was caught ${error.message}`);
        });

**Comment by hoanghiep1x0** [comment]
Have you defined the model for it?

**Comment by taylor009** [comment]
Yeah @hoanghiep1x0  sorry for leaving out my model code:

`
'use strict';

module.exports =
  {
      labels           : ['Skill'],
      language         : 'string',
      yearsOfExperience: 'integer',
      generalArea      : {
          type   : 'string',
          indexed: true,
      },
  };
`


Here is how my app code looks like as well:

`const express    = require('express');
const morgan     = require('morgan');
const bodyParser = require('body-parser');
const logger     = require('./config/logger');
const Neode = require('neode');

// Routes
// const skillsRoute = require('./routes/skills');

const neode = new Neode('bolt://localhost:7687', 'neo4j', 'bestone009');

neode.withDirectory(__dirname+'/models');

neode.schema.install().then(() => console.info('Schema Installed'));

const app = express();

app.use(function(req, res, next)
{
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'X-Requested-With');
    next();
});

app.use(morgan('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));

app.get('/', (req, res, next) =>
{
    res.send('Hello world Home Page');
    next();
});

app.use(require('./routes/skills')(neode));


module.exports = app;`

**Comment by adam-cowley** [comment]
Do you have a repository that I can clone to take a look?

**Comment by taylor009** [comment]
@adam-cowley I actually removed the code from the project. I'll need to add again then you can take a look at it.

**Comment by adam-cowley** [comment]
OK I see the problem.

You've not registered any models in the neode instance, so it doesn't have a definition for Skill.  You could either do:

```js
neode.with({
    Skill: require('./models/skill')  // This way you're explicitly naming the model as 'Skill'
})
```
Or the following will automatically register every file in the models directory.
```js
neode.withDirectory(__dirname+'/models')
```

But, if you choose the second option - your file `src/models/skill.js` is in lowercase so to make the code work you'd need to rename the file to *S*kill or call `neode.create('skill', {...})`.

I'll add a more user friendly error message to the next release to make this clearer.

**Comment by taylor009** [comment]
Thanks, @adam-cowley  works great now.
