### ISSUE TITLE
Can dependencies 'fsevents'  be optional?

### ISSUE THREAD

**Issue by morishjs** [adam-cowley/neode#88]
My dev environment is MacOS but the production server is running on Linux.
and got a error from console when I deployed and installed the packages.

`npm ERR! notsup Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

I guess this message is from `packages.json` that does not specify `fsevents` as optional.

**Comment by adam-cowley** [comment]
I'm not sure how that got there, I have removed it in version 0.3.5
