### ISSUE TITLE
rel.from rel.to not a function on relateTo()

### ISSUE THREAD

**Issue by WillianRod** [adam-cowley/neode#92]
I'm trying to create a leationship between two nodes. The relationship is being create successfully but the only problem is that I can't retrieve the nodes from and to, because  rel.from() is not a function neither rel.to().

How can I solve that?

```javascript
Promise.all([
    instance.first('Aluno', 'ra', from),
    instance.first('Aluno', 'ra', to),
]).then(([a, b]) => {
    a.relateTo(b, 'friends', { since: new Date() })
        .then(rel => {
            console.log(typeof rel.from, typeof rel.to, typeof rel.properties); // undefined, undefined, function
        });
});
```

**Comment by adam-cowley** [comment]
Try calling the functions for `rel.startNode()`, `rel.endNode()` and `rel.properties()`
